name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        run:
          git remote add gitlab <https://gitlab.com/sanchezdev/jumping-chickens.git>
          git push gitlab HEAD:main
